name: pipeline
on:
  schedule:
    - cron: '58,02 02,03 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: checkout repo
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install requests==2.32.3 pandas==2.0.3 psycopg2==2.9.9 python-decouple==3.8

        

      - name: run script
        run: python ./main.py

      - name: commit and push files
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Update files
    
